// Code generated by sdk/gen/gen_clients.py. DO NOT EDIT.

package cli

import (
	"context"
	"fmt"
	"net/url"

	dogabot "github.com/dogabot/dogabot-sdk-go"
)

// Call invokes the SDK method for operationId with path/query/body.
func Call(
	c *dogabot.Client,
	ctx context.Context,
	operationID string,
	pathParams map[string]string,
	query url.Values,
	body any,
	opts ...dogabot.RequestOption,
) (any, error) {
	if len(query) > 0 {
		opts = append([]dogabot.RequestOption{dogabot.WithQuery(query)}, opts...)
	}
	switch operationID {
	case "getMe":
		return c.GetMe(ctx, opts...)
	case "getMeStatistics":
		return c.GetMeStatistics(ctx, opts...)
	case "getMePositions":
		return c.GetMePositions(ctx, opts...)
	case "getMePositionlegs":
		return c.GetMePositionlegs(ctx, opts...)
	case "getMeOrders":
		return c.GetMeOrders(ctx, opts...)
	case "getMeSignals":
		return c.GetMeSignals(ctx, opts...)
	case "getMeEmitters":
		return c.GetMeEmitters(ctx, opts...)
	case "postMeEmittersSummary":
		return c.PostMeEmittersSummary(ctx, body, opts...)
	case "postAutomationsSummary":
		return c.PostAutomationsSummary(ctx, body, opts...)
	case "getFollowers":
		return c.GetFollowers(ctx, opts...)
	case "postFollowers":
		return c.PostFollowers(ctx, body, opts...)
	case "getFollowersById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetFollowersById(ctx, id, opts...)
	case "patchFollowersById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PatchFollowersById(ctx, id, body, opts...)
	case "deleteFollowersById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.DeleteFollowersById(ctx, id, body, opts...)
	case "postFollowersSummary":
		return c.PostFollowersSummary(ctx, body, opts...)
	case "getFollowersSummaryById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetFollowersSummaryById(ctx, id, opts...)
	case "getFollowersPnlseriesById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetFollowersPnlseriesById(ctx, id, opts...)
	case "getFollowersPositionById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetFollowersPositionById(ctx, id, opts...)
	case "getBots":
		return c.GetBots(ctx, opts...)
	case "postBots":
		return c.PostBots(ctx, body, opts...)
	case "getBotsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetBotsById(ctx, id, opts...)
	case "patchBotsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PatchBotsById(ctx, id, body, opts...)
	case "deleteBotsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.DeleteBotsById(ctx, id, body, opts...)
	case "postBotsSummary":
		return c.PostBotsSummary(ctx, body, opts...)
	case "getBotsPnlseriesById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetBotsPnlseriesById(ctx, id, opts...)
	case "getBotsPositionById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetBotsPositionById(ctx, id, opts...)
	case "getEmitters":
		return c.GetEmitters(ctx, opts...)
	case "postEmitters":
		return c.PostEmitters(ctx, body, opts...)
	case "getEmittersById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetEmittersById(ctx, id, opts...)
	case "patchEmittersById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PatchEmittersById(ctx, id, body, opts...)
	case "deleteEmittersById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.DeleteEmittersById(ctx, id, body, opts...)
	case "postEmittersSummary":
		return c.PostEmittersSummary(ctx, body, opts...)
	case "getEmittersSummaryById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetEmittersSummaryById(ctx, id, opts...)
	case "getEmittersCurated":
		return c.GetEmittersCurated(ctx, opts...)
	case "getEmittersPnlseriesById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetEmittersPnlseriesById(ctx, id, opts...)
	case "getEmittersPositionById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetEmittersPositionById(ctx, id, opts...)
	case "getPortfolios":
		return c.GetPortfolios(ctx, opts...)
	case "postPortfolios":
		return c.PostPortfolios(ctx, body, opts...)
	case "getPortfoliosById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetPortfoliosById(ctx, id, opts...)
	case "patchPortfoliosById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PatchPortfoliosById(ctx, id, body, opts...)
	case "deletePortfoliosById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.DeletePortfoliosById(ctx, id, body, opts...)
	case "postPortfoliosSummary":
		return c.PostPortfoliosSummary(ctx, body, opts...)
	case "getPortfoliosPnlseriesById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetPortfoliosPnlseriesById(ctx, id, opts...)
	case "getPortfoliosPositionsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetPortfoliosPositionsById(ctx, id, opts...)
	case "getOrders":
		return c.GetOrders(ctx, opts...)
	case "getSignals":
		return c.GetSignals(ctx, opts...)
	case "getBacktestQuota":
		return c.GetBacktestQuota(ctx, opts...)
	case "getBacktests":
		return c.GetBacktests(ctx, opts...)
	case "getBacktestsSummary":
		return c.GetBacktestsSummary(ctx, opts...)
	case "getBacktestByJob_id":
		jobID, ok := pathParams["job_id"]
		if !ok || jobID == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "job_id")
		}
		return c.GetBacktestByJob_id(ctx, jobID, opts...)
	case "getBacktestSignalsByJob_id":
		jobID, ok := pathParams["job_id"]
		if !ok || jobID == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "job_id")
		}
		return c.GetBacktestSignalsByJob_id(ctx, jobID, opts...)
	case "getBacktestBulkSeed":
		return c.GetBacktestBulkSeed(ctx, opts...)
	case "getBacktestBulkBatches":
		return c.GetBacktestBulkBatches(ctx, opts...)
	case "getBacktestBulkBatchesByBatch_id":
		batch_id, ok := pathParams["batch_id"]
		if !ok || batch_id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "batch_id")
		}
		return c.GetBacktestBulkBatchesByBatch_id(ctx, batch_id, opts...)
	case "getTicker":
		return c.GetTicker(ctx, opts...)
	case "getFundingrate":
		return c.GetFundingrate(ctx, opts...)
	case "getMarketOrderbook":
		return c.GetMarketOrderbook(ctx, opts...)
	case "getMarketTrades":
		return c.GetMarketTrades(ctx, opts...)
	case "getMarkets":
		return c.GetMarkets(ctx, opts...)
	case "getMarketsAssetprofile":
		return c.GetMarketsAssetprofile(ctx, opts...)
	case "getExchanges":
		return c.GetExchanges(ctx, opts...)
	case "getMarkettypes":
		return c.GetMarkettypes(ctx, opts...)
	case "getMarketplaceSearch":
		return c.GetMarketplaceSearch(ctx, opts...)
	case "getMarketplaceSellersByHandle":
		handle, ok := pathParams["handle"]
		if !ok || handle == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "handle")
		}
		return c.GetMarketplaceSellersByHandle(ctx, handle, opts...)
	case "getDatafeedHistory":
		return c.GetDatafeedHistory(ctx, opts...)
	case "postMarketsSymbolcorrelation":
		return c.PostMarketsSymbolcorrelation(ctx, body, opts...)
	case "postMarketsSymbolvolatility":
		return c.PostMarketsSymbolvolatility(ctx, body, opts...)
	case "postMarketsSymbolfeebreakeven":
		return c.PostMarketsSymbolfeebreakeven(ctx, body, opts...)
	case "getTerminalOrders":
		return c.GetTerminalOrders(ctx, opts...)
	case "getTerminalOrdersByclientorderidByClient_order_id":
		clientOrderID, ok := pathParams["client_order_id"]
		if !ok || clientOrderID == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "client_order_id")
		}
		return c.GetTerminalOrdersByclientorderidByClient_order_id(ctx, clientOrderID, opts...)
	case "getTerminalPositions":
		return c.GetTerminalPositions(ctx, opts...)
	case "getTerminalSymbolrules":
		return c.GetTerminalSymbolrules(ctx, opts...)
	case "getTerminalOrdercapabilities":
		return c.GetTerminalOrdercapabilities(ctx, opts...)
	case "getExchangeBalances":
		return c.GetExchangeBalances(ctx, opts...)
	case "getExchangePositions":
		return c.GetExchangePositions(ctx, opts...)
	case "getExchangeMarginsummary":
		return c.GetExchangeMarginsummary(ctx, opts...)
	case "getExchangeOrders":
		return c.GetExchangeOrders(ctx, opts...)
	case "getExchangeTrades":
		return c.GetExchangeTrades(ctx, opts...)
	case "getExchangeIncome":
		return c.GetExchangeIncome(ctx, opts...)
	case "getExchangeOpenablenotional":
		return c.GetExchangeOpenablenotional(ctx, opts...)
	case "postExchangeLeverage":
		return c.PostExchangeLeverage(ctx, body, opts...)
	case "postExchangeCancelorder":
		return c.PostExchangeCancelorder(ctx, body, opts...)
	case "postExchangeCancelorders":
		return c.PostExchangeCancelorders(ctx, body, opts...)
	case "getCredentials":
		return c.GetCredentials(ctx, opts...)
	case "postCredentials":
		return c.PostCredentials(ctx, body, opts...)
	case "getTags":
		return c.GetTags(ctx, opts...)
	case "postTags":
		return c.PostTags(ctx, body, opts...)
	case "getMeStatisticsBytag":
		return c.GetMeStatisticsBytag(ctx, opts...)
	case "postFollowersStartById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostFollowersStartById(ctx, id, opts...)
	case "postFollowersStopById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostFollowersStopById(ctx, id, opts...)
	case "postBotsStartById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostBotsStartById(ctx, id, opts...)
	case "postBotsStopById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostBotsStopById(ctx, id, opts...)
	case "postBotsBooksById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostBotsBooksById(ctx, id, body, opts...)
	case "postFollowersBooksById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostFollowersBooksById(ctx, id, body, opts...)
	case "postEmittersStartById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostEmittersStartById(ctx, id, opts...)
	case "postEmittersStopById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostEmittersStopById(ctx, id, opts...)
	case "postPortfoliosStartById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostPortfoliosStartById(ctx, id, opts...)
	case "postPortfoliosStopById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostPortfoliosStopById(ctx, id, opts...)
	case "putFollowersTagsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PutFollowersTagsById(ctx, id, body, opts...)
	case "putBotsTagsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PutBotsTagsById(ctx, id, body, opts...)
	case "putEmittersTagsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PutEmittersTagsById(ctx, id, body, opts...)
	case "putPortfoliosTagsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PutPortfoliosTagsById(ctx, id, body, opts...)
	case "patchTagsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PatchTagsById(ctx, id, body, opts...)
	case "deleteTagsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.DeleteTagsById(ctx, id, body, opts...)
	case "putCredentialsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PutCredentialsById(ctx, id, body, opts...)
	case "deleteCredentialsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.DeleteCredentialsById(ctx, id, body, opts...)
	case "postCredentialsDefaultById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostCredentialsDefaultById(ctx, id, opts...)
	case "postBacktest":
		return c.PostBacktest(ctx, body, opts...)
	case "postBacktestBulk":
		return c.PostBacktestBulk(ctx, body, opts...)
	case "postBacktestBulkBatchesRerunByBatch_id":
		batch_id, ok := pathParams["batch_id"]
		if !ok || batch_id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "batch_id")
		}
		return c.PostBacktestBulkBatchesRerunByBatch_id(ctx, batch_id, opts...)
	case "postBacktestBulkBatchesCancelByBatch_id":
		batch_id, ok := pathParams["batch_id"]
		if !ok || batch_id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "batch_id")
		}
		return c.PostBacktestBulkBatchesCancelByBatch_id(ctx, batch_id, opts...)
	case "postBacktestCancelByJob_id":
		jobID, ok := pathParams["job_id"]
		if !ok || jobID == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "job_id")
		}
		return c.PostBacktestCancelByJob_id(ctx, jobID, opts...)
	case "postTerminalPlaceorder":
		return c.PostTerminalPlaceorder(ctx, body, opts...)
	case "postTerminalCancelorder":
		return c.PostTerminalCancelorder(ctx, body, opts...)
	case "getAiChatQuota":
		return c.GetAiChatQuota(ctx, opts...)
	case "getAiChatConversations":
		return c.GetAiChatConversations(ctx, opts...)
	case "postAiChatConversations":
		return c.PostAiChatConversations(ctx, body, opts...)
	case "getAiChatConversationsById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.GetAiChatConversationsById(ctx, id, opts...)
	case "postAiChatConversationsMessagesById":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		return c.PostAiChatConversationsMessagesById(ctx, id, body, opts...)
	case "postAiChatConversationsToolsConfirmByIdCall_id":
		id, ok := pathParams["id"]
		if !ok || id == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "id")
		}
		callID, ok := pathParams["call_id"]
		if !ok || callID == "" {
			return nil, fmt.Errorf("missing required path parameter %s", "call_id")
		}
		return c.PostAiChatConversationsToolsConfirmByIdCall_id(ctx, id, callID, body, opts...)
	default:
		return nil, fmt.Errorf("unknown operationId %q", operationID)
	}
}
